version: '3'

services:
  bb-api: 
    container_name: bb-api
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
     - NODE_ENV=local
     - ES_HOST=bb-data
     - PORT=3000
    volumes:
      - ./books:/usr/src/app/books

  bb-app: 
    container_name: bb-app
    image: nginx
    volumes: 
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80" 

  bb-data: 
    container_name: bb-data
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: 
      - ./data:/usr/share/elasticsearch/data
    environment:
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - "9300:9300"
      - "9200:9200"
